### PR TITLE
Update week1.md

### PR DESCRIPTION
**Pull request by beeburrt**
Fix spelling mistake

### CODE REVIEW

**Comment by beeburrt** [comment]
Question concerning the following paragraph:

> For instance, suppose the www-page contains a form to log in into the website. It's clear that password and user name have to be checked on the server. On the other hand, we can allow the browser Javascript to check whether the user name box is empty when they try to log in. In such situations it is useless to bother the browser at all, because the log in would never succeed.

In that last sentence of this paragraph, should the word "browser" be changed to server? As in: "...it is useless to bother the server at all..."

Just checking. Thank you so much for this course, you're the best!

**Comment by mluukkai** [comment]
yes! it indeed should be server

**Comment by beeburrt** [comment]
I hope I'm doing this right. Is it ok that I'm pushing multiple commits to the same branch?

**Comment by beeburrt** [comment]
I'm not sure how to fix this sentence:

> The command starts a Puma HTTP server (see https://github.com/puma/puma) by default, which begins to execute the Rails application he directory.

It looks like maybe just deleting the last two words? That sentence is line 162 on here. About 2 or 3 paragraphs before exercise 3

**Comment by beeburrt** [comment]
The first migration we run, shouldn't it be `rails db:migrate` ? 

The course documentation says to run `rake db:migrate` 

And the error message says to run:

> bin/rails db:migrate RAILS_ENV=development

**Pull request closed without merging**
